// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @dev 中文维护契约：本合约不实现 Groth16 配对运算，而是把证明点与公共输入按固定 ABI `staticcall` 给 owner 指定的两个 verifier，并保存成功结果。
 * @dev 任意账户都可提交证明；owner 可随时替换 verifier 且地址不做代码/接口校验，所以“verified”只表示当时目标地址对该 payload 返回可解码的 true。
 * @dev 审计分证明的电路公共输入只有六维分、overallScore、inputCommitment，函数参数 tokenId/auditId 没有进入 verifier；调用者必须在链外另行保证记录归属。
 * @dev 指纹证明把 tokenId 纳入公共输入，但 developerHash 只是域元素，合约不把它映射到 msg.sender 或 EVM 地址；所有权含义依赖链外哈希规范和秘密管理。
 * @dev 全局 proofHash 只覆盖 a/b/c 并防止同一证明点再次登记；同一 token/audit 仍可用不同有效证明覆盖，auditProofCount 会继续增加，指纹映射只保留最新项。
 * @dev verifier 未配置、证明重放、验证返回 false/回退/短返回值都会回滚且不写状态；8/3 个公共输入的顺序与 snarkjs 生成 ABI 是不可漂移的兼容约束。
 * @title ZkAuditVerifier
 * @notice Stores and verifies ZK proofs for audit score correctness and agent fingerprints.
 *
 * Two proof types:
 *   1. Audit Score Proof — proves dimensional scores were correctly computed from raw data
 *   2. Agent Fingerprint Proof — proves agent identity is bound to NFT without revealing code
 *
 * The Groth16 verifier contracts are auto-generated by snarkjs from the circom circuits.
 * This contract acts as a registry that stores proof verification results on-chain.
 */
contract ZkAuditVerifier {
    // --- Types ---

    struct AuditScoreProof {
        uint256 tokenId;
        uint256 auditId;
        uint256[6] dimensionalScores;
        uint256 overallScore;
        uint256 inputCommitment;
        bool verified;
        uint256 verifiedAt;
        bytes32 proofHash;        // keccak256 of the raw proof for dedup
    }

    struct AgentFingerprintProof {
        uint256 tokenId;
        uint256 fingerprintHash;
        uint256 developerHash;
        bool verified;
        uint256 verifiedAt;
        bytes32 proofHash;
    }

    // --- Events ---

    event AuditScoreProofVerified(
        uint256 indexed tokenId,
        uint256 indexed auditId,
        uint256 overallScore,
        uint256 inputCommitment,
        bytes32 proofHash
    );

    event AgentFingerprintProofVerified(
        uint256 indexed tokenId,
        uint256 fingerprintHash,
        uint256 developerHash,
        bytes32 proofHash
    );

    event AuditScoreVerifierUpdated(address indexed oldVerifier, address indexed newVerifier);
    event FingerprintVerifierUpdated(address indexed oldVerifier, address indexed newVerifier);

    // --- State ---

    address public owner;

    // Groth16 verifier contract addresses (set after deployment)
    address public auditScoreVerifierContract;
    address public fingerprintVerifierContract;

    // tokenId => auditId => proof record
    mapping(uint256 => mapping(uint256 => AuditScoreProof)) public auditScoreProofs;

    // tokenId => latest fingerprint proof
    mapping(uint256 => AgentFingerprintProof) public fingerprintProofs;

    // tokenId => number of verified audit proofs
    mapping(uint256 => uint256) public auditProofCount;

    mapping(bytes32 => bool) private _usedProofHashes;

    // --- Modifiers ---

    modifier onlyOwner() {
        require(msg.sender == owner, "NOT_OWNER");
        _;
    }

    // --- Constructor ---

    constructor() {
        owner = msg.sender;
    }

    // --- Admin ---

    function setAuditScoreVerifier(address _verifier) external onlyOwner {
        address old = auditScoreVerifierContract;
        auditScoreVerifierContract = _verifier;
        emit AuditScoreVerifierUpdated(old, _verifier);
    }

    function setFingerprintVerifier(address _verifier) external onlyOwner {
        address old = fingerprintVerifierContract;
        fingerprintVerifierContract = _verifier;
        emit FingerprintVerifierUpdated(old, _verifier);
    }

    // --- Verify & Store: Audit Score Proof ---

    /**
     * @notice Verify a ZK proof that audit scores were correctly computed.
     * @dev tokenId 与 auditId 仅作为本登记表的映射键和事件字段，当前 AuditScoreVerifier 电路未约束二者；同一键的后续有效证明会覆盖旧结构体。
     * @param tokenId The agent's NFT token ID
     * @param auditId The audit ID being proven
     * @param dimensionalScores The 6 claimed dimensional scores [0-100]
     * @param overallScore The claimed weighted overall score [0-100]
     * @param inputCommitment Poseidon hash binding the proof to private inputs
     * @param a Groth16 proof point A
     * @param b Groth16 proof point B
     * @param c Groth16 proof point C
     */
    function verifyAuditScore(
        uint256 tokenId,
        uint256 auditId,
        uint256[6] calldata dimensionalScores,
        uint256 overallScore,
        uint256 inputCommitment,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c
    ) external returns (bool) {
        require(auditScoreVerifierContract != address(0), "VERIFIER_NOT_SET");
        bytes32 proofHash = _proofHash(a, b, c);
        require(!_usedProofHashes[proofHash], "PROOF_REPLAYED");

        // Build public inputs array matching circuit: [dim0..5, overall, commitment]
        uint256[8] memory pubInputs;
        for (uint256 i = 0; i < 6; i++) {
            pubInputs[i] = dimensionalScores[i];
        }
        pubInputs[6] = overallScore;
        pubInputs[7] = inputCommitment;

        // Call the Groth16 verifier
        bool valid = _callGroth16Verifier(
            auditScoreVerifierContract,
            a, b, c,
            pubInputs,
            8
        );

        require(valid, "INVALID_PROOF");

        _usedProofHashes[proofHash] = true;

        auditScoreProofs[tokenId][auditId] = AuditScoreProof({
            tokenId: tokenId,
            auditId: auditId,
            dimensionalScores: dimensionalScores,
            overallScore: overallScore,
            inputCommitment: inputCommitment,
            verified: true,
            verifiedAt: block.timestamp,
            proofHash: proofHash
        });

        auditProofCount[tokenId] += 1;

        emit AuditScoreProofVerified(tokenId, auditId, overallScore, inputCommitment, proofHash);

        return true;
    }

    // --- Verify & Store: Agent Fingerprint Proof ---

    /**
     * @notice Verify a ZK proof binding an agent identity to its NFT.
     * @dev 该入口验证“存在满足电路约束的 secret/manifest/code/traits”，不会验证 tokenId 在身份合约中存在，也不会检查提交者就是 developerHash 对应主体。
     * @param tokenId The agent's NFT token ID
     * @param fingerprintHash The public fingerprint hash
     * @param developerHash The developer ownership hash
     * @param a Groth16 proof point A
     * @param b Groth16 proof point B
     * @param c Groth16 proof point C
     */
    function verifyFingerprint(
        uint256 tokenId,
        uint256 fingerprintHash,
        uint256 developerHash,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c
    ) external returns (bool) {
        require(fingerprintVerifierContract != address(0), "VERIFIER_NOT_SET");
        bytes32 proofHash = _proofHash(a, b, c);
        require(!_usedProofHashes[proofHash], "PROOF_REPLAYED");

        // Public inputs: [fingerprintHash, tokenId, developerHash]
        uint256[8] memory pubInputs;
        pubInputs[0] = fingerprintHash;
        pubInputs[1] = tokenId;
        pubInputs[2] = developerHash;

        bool valid = _callGroth16Verifier(
            fingerprintVerifierContract,
            a, b, c,
            pubInputs,
            3
        );

        require(valid, "INVALID_PROOF");

        _usedProofHashes[proofHash] = true;

        fingerprintProofs[tokenId] = AgentFingerprintProof({
            tokenId: tokenId,
            fingerprintHash: fingerprintHash,
            developerHash: developerHash,
            verified: true,
            verifiedAt: block.timestamp,
            proofHash: proofHash
        });

        emit AgentFingerprintProofVerified(tokenId, fingerprintHash, developerHash, proofHash);

        return true;
    }

    // --- Query ---

    function getAuditScoreProof(uint256 tokenId, uint256 auditId)
        external view returns (AuditScoreProof memory)
    {
        return auditScoreProofs[tokenId][auditId];
    }

    function getFingerprintProof(uint256 tokenId)
        external view returns (AgentFingerprintProof memory)
    {
        return fingerprintProofs[tokenId];
    }

    function isAuditScoreVerified(uint256 tokenId, uint256 auditId)
        external view returns (bool)
    {
        return auditScoreProofs[tokenId][auditId].verified;
    }

    function isFingerprintVerified(uint256 tokenId)
        external view returns (bool)
    {
        return fingerprintProofs[tokenId].verified;
    }

    function isProofHashUsed(bytes32 proofHash) external view returns (bool) {
        return _usedProofHashes[proofHash];
    }

    // --- Internal: Generic Groth16 Verifier Call ---

    /// @dev proofHash 不含公共输入、verifier 地址、tokenId 或 auditId；其职责仅是对完全相同的 Groth16 证明点做全局一次性消费。
    function _proofHash(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c
    ) internal pure returns (bytes32) {
        return keccak256(abi.encode(a, b, c));
    }

    /// @dev 低级调用严格匹配 snarkjs 生成 verifier 的定长数组签名；目标回退或返回少于 32 字节统一视为无效，其他输入数量直接拒绝。
    function _callGroth16Verifier(
        address verifier,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[8] memory pubInputs,
        uint256 numInputs
    ) internal view returns (bool) {
        // snarkjs-generated verifiers expose:
        //   verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[N] input) → bool
        // We encode the call dynamically based on numInputs
        bytes memory payload;

        if (numInputs == 8) {
            payload = abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[8])",
                a, b, c, pubInputs
            );
        } else if (numInputs == 3) {
            uint256[3] memory inputs3;
            for (uint256 i = 0; i < 3; i++) {
                inputs3[i] = pubInputs[i];
            }
            payload = abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[3])",
                a, b, c, inputs3
            );
        } else {
            revert("UNSUPPORTED_INPUT_COUNT");
        }

        (bool success, bytes memory result) = verifier.staticcall(payload);
        if (!success || result.length < 32) {
            return false;
        }
        return abi.decode(result, (bool));
    }
}
